name: GitHub-Profile-Summary-Cards

on:
  schedule:
      # execute every 24 hours
    # - cron: "* */24 * * *"
      # every 6 hours
    # - cron: '0 * * * *'
      # every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: GitHub Profile Summary Cards
      #   uses: vn7n24fzkq/github-profile-summary-cards@release
      #   env: # default use ${{ secrets.GITHUB_TOKEN }}, you should replace with your personal access token
      #     GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
      #   with:
      #     USERNAME: ${{ github.repository_owner }}
      - name: Generates a snake game
        uses: Platane/snk@master
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}
          # path of the generated gif file
          # If left empty, the gif file will not be generated
          gif_out_path: dist/github-snake.gif
          # path of the generated svg file
          # If left empty, the svg file will not be generated
          svg_out_path: dist/github-snake.svg
      # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status
      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
