name: GitHub-Profile-Summary-Cards

on:
  schedule:
      # execute every 24 hours
    # - cron: "* */24 * * *"
      # every 6 hours
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env: # default use ${{ secrets.GITHUB_TOKEN }}, you should replace with your personal access token
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      - uses: Platane/snk@master
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}

          # path of the generated gif file
          # If left empty, the gif file will not be generated
          gif_out_path: dist/github-snake.gif

          # path of the generated svg file
          # If left empty, the svg file will not be generated
          svg_out_path: dist/github-snake.svg
